### ISSUE TITLE
unbreak code for lifewire.com

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#10]
This filter from [uBOPa.txt](https://raw.githubusercontent.com/nimasaj/uBOPa/master/uBOPa.txt), blocks the main section in [lifewire.com](https://lifewire.com):
```
##*[class*="-ad-container"]
```

This code unbreaks it:
```
lifewire.com#@#*[class*="-ad-container"]
```

**Comment by nimasaj** [comment]
Thanks for reporting the issue. Even though I couldn't reproduce the issue on my side, but since the whitelist is not bringing back the ads, it's added on https://github.com/nimasaj/uBOPa/commit/f04369d21640707709aa3152de02360433fe4723
