### ISSUE TITLE
unbreak code for filecr.com

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#11]
#https://github.com/uBlockOrigin/uAssets/issues/10734

The `*/ads.*` filter on your list is triggering the anti-adblock on _filecr.com_ by blocking this script:
[https://filecr.com/wp-content/plugins/deblocker/js/ads.js](https://filecr.com/wp-content/plugins/deblocker/js/ads.js 
)

Example:
[https://filecr.com/windows/internet-download-manager?id=5887869221](https://filecr.com/windows/internet-download-manager?id=5887869221)

This filter fixes that issue:
`@@||filecr.com/wp-content/plugins/deblocker/js/ads.js$script,1p`

**Comment by nimasaj** [comment]
Thanks for reporting the issue. It's fixed now on https://github.com/nimasaj/uBOPa/commit/f8acd8af5d5b00dae2db94f729f29f596afb9a35.
