### ISSUE TITLE
unbreak code for adlock.com

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#12]
These filters from your list, break adlock.com ([Example](https://adlock.com/blog/how-to-stop-ad-blocker-detection-on-websites/)):
```
*##a[href*="-ads/"]
*##a[href*="-ads-"]>img
*##*[class*="-ads "]
```

These codes unbreak the site:
```
adlock.com#@#a[href*="-ads/"]
adlock.com#@#a[href*="-ads-"]>img
adlock.com#@#*[class*="-ads "]
```

**Comment by nimasaj** [comment]
Thanks for reporting the issue. It's fixed now on f8acd8a.
