### ISSUE TITLE
Ads and trackers

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#14]
```
! anti right-click and anti select

||fa-tools.ir/code/rightclick/right-click1.js
||seyedrezabazyar.com/codetools/files/close-right-click.js
||1abzaar.ir/abzar/tools/no-rightclick.js
||1abzaar.ir/abzar/tools/no-selects.js
||tool.4tools.ir/tools/click-l/click-l.js
||takskin.com/abzar/norightclick/norightclick.js
blogfa.com##+js(set, disableselect, true)
```
```
! tracking

||abzarfa.com/services/minicounter/counter.php
||k2cod.com/statistics/counter.php
||1abzar.ir/abzar/tools/stat/
||1abzar.ir/abzar/tools/post-view/
||counter.toolsir.com
```

```
!ads

par30games.net##.fixedbanner

moderndl.com##.pushe-content-wrapper

farsroid.com##.cas-pubg.cas

uupload.ir##.links_footer

8pic.ir##.links_footer
8pic.ir##.link-button

imgurl.ir##.links_footer

uplooder.net##.special_links

upload-fa.ir##.tagslist
upload-fa.ir##.footer_nav
upload-fa.ir##.banners

! rozblog.com ads system
||rozblog.com/include/rozblog_ads_js.php

! picofile.com download page
||utopclick.com/b/$image
```

**Comment by nimasaj** [comment]
Thanks for reporting them.
Regarding tracker and annoyances (e.g. disabling right-click), I'm not sure to merge those rules with this filter list. I will probably make a separate list for them.

Regarding the ads,
most of them were added on f8acd8a. For the last one, please provide an example link.
```
! picofile.com download page
||utopclick.com/b/$image
```

Regarding `upload-fa.ir##.footer_nav`, I guess this is a part of website design and not ads, Please correct me if I'm wrong.

**Comment by MasterKia** [comment]
[picofile.com download page ads example](https://s8.picofile.com/file/8277642834/index.html.html)

`upload-fa.ir##.footer_nav example:`
![Break4](https://user-images.githubusercontent.com/17685483/144836650-8a86731f-14e3-41f8-a5d0-1cba773254d3.png)

**Comment by nimasaj** [comment]
These are added on https://github.com/nimasaj/uBOPa/commit/5f2bfca0e4ca93e6a9e06e4608707ad089ddbd97.

**Comment by MasterKia** [comment]
> Regarding tracker and annoyances (e.g. disabling right-click), I'm not sure to merge those rules with this filter list.

Addressed in `https://github.com/farrokhi/adblock-iran/commit/7d3e5cdda2560b2f2404d01135c8f3d6674e5799` and `https://github.com/farrokhi/adblock-iran/commit/9a503feac6e14886fad71c758576c4fdeb80ec73`, Closing.
