### ISSUE TITLE
unbreak code for web.tosino.com

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#15]
[Example link](https://web.tosinso.com/fa/articles/41462/4-%D9%86%D9%85%D9%88%D9%86%D9%87-%DA%A9%D8%AF-%D8%A8%D8%B1%D8%A7%DB%8C-%D8%AC%D9%84%D9%88%DA%AF%DB%8C%D8%B1%DB%8C-%D8%A7%D8%B2-%D8%B1%D8%A7%D8%B3%D8%AA-%DA%A9%D9%84%DB%8C%DA%A9-%D9%88-%DA%A9%D9%BE%DB%8C-%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA-%D9%88%D8%A8-%D8%B3%D8%A7%DB%8C%D8%AA)

Unbreak code:
`@@||resources.tosinso.com/js/components/general/adv-input.vue?t=v334$xhr,domain=web.tosinso.com`

**Reason:**
![Break3](https://user-images.githubusercontent.com/17685483/144826540-e7e8ae72-cb08-429c-957c-7bc4d8eb8ec8.png)
**Broken:**
![Break1](https://user-images.githubusercontent.com/17685483/144826530-9eec5355-e141-4a69-bd5f-8577b048788b.png)
**Unbreak:**
![Break2](https://user-images.githubusercontent.com/17685483/144826537-4bfe04fb-f14f-4ed2-8e28-029a5903d5f0.png)

**Comment by nimasaj** [comment]
Thanks for reporting the issue. It's fixed now on f8acd8a.
