### ISSUE TITLE
moderndl.com ads and breakage

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#16]
Fix 1: `moderndl.com##.pushe-prompt-is-rtl.pushe-prompt-top-center.pushe-prompt-top.prompt`
Fix 2:
```
moderndl.com#@#*[id^="ads_"]
moderndl.com#@#*[alt*="تبلیغ"]
```
Fix 3: `moderndl.com##.m-ads`

![Break5](https://user-images.githubusercontent.com/17685483/144848305-a1c70b85-3182-48e8-ac18-293368d0780d.png)
![Break6](https://user-images.githubusercontent.com/17685483/144848312-0c264e19-a70e-4535-b71b-676ea1d9263b.png)
![Break7](https://user-images.githubusercontent.com/17685483/144848384-bebee327-b652-4b56-bff6-ec115dee7df1.png)

**Comment by nimasaj** [comment]
Thanks for reporting the issues.
Nr.1 cannot be applied since this is not an ad issue, but a website issue. Website developer should fix it either using cookies to avoid popping it up all the time, or some other methods to stop it.

The other suggestions were made into the list, https://github.com/nimasaj/uBOPa/commit/4009d33ac8673508e1d4c26c7dc758e673e81582.

**Comment by MasterKia** [comment]
Then the first issue should be addressed in the (upcoming?) annoyances filter.

**Comment by MasterKia** [comment]
_Update_

`##.pushe-prompt-is-rtl.pushe-prompt-top-center.pushe-prompt-top.prompt` example on moderndl.com and filmvision.ir:
![image](https://user-images.githubusercontent.com/17685483/147445860-94882984-6700-48de-924a-32f737104203.png)

**Comment by nimasaj** [comment]
I see this is coming to more and more websites and it's not a specific website issue, therefore, it can be added to the list, https://github.com/nimasaj/uBOPa/commit/4b99f83e5d88e5a2768baf62795ba87cc8ceb6ea.
To record more samples, the following websites are also using this script.
`https://mybia4music.com/` 
`https://www.shirazsong.in/`
`https://nicmusic.net/`
`https://www.jenabmusic.com/`


Please check out with the updated list and report if it works for you.

**Comment by MasterKia** [comment]
Thanks for the investigation of this issue, it's fixed with the latest commit.
