### ISSUE TITLE
grammarly.com breakage

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#17]
Some filters from your list break this webpage and the close (x) button wouldn't work.
Solution:
```
@@||contenthub-static.grammarly.com/assets/js/desktop/*/shared-components-install_banner.client.js$script,domain=grammarly.com
@@||contenthub-static.grammarly.com/assets/styles/desktop/*/shared-components-install_banner.css$stylesheet,domain=grammarly.com
```

Broken:
![Break8](https://user-images.githubusercontent.com/17685483/145528498-607eeca1-81c0-4244-a160-99c0e2710bd9.png)

Unbreak:
![Break9](https://user-images.githubusercontent.com/17685483/145528504-c15ca988-7082-4cc6-bf8d-dd4a7ebc0e0e.png)

Reason:
![Break10](https://user-images.githubusercontent.com/17685483/145528506-a231fcad-3091-40d0-9529-ab83ac1c7873.png)

**Comment by nimasaj** [comment]
Could you please explain how to reproduce the issue, step by step, and provide an example link if it's possible?
I do not find any blocked content from uBOPa on my side, both in the homepage as a guest user and also after creating an account and logging into it in the dashboard.
The blocked content on my side is visible in the following screenshot and none of them is coming from uBOPa, `https://gcdn.pbrd.co/images/D7vaG05gxQ5O.png`

**Comment by MasterKia** [comment]
Does the reproduce the issue?
https://www.grammarly.com/blog/learned-learnt/

**Comment by nimasaj** [comment]
Thanks for reporting the issue. It's fixed now on https://github.com/nimasaj/uBOPa/commit/39bab4a930798f7075b4bc85286b0936aa8987a6.
