### ISSUE TITLE
takblog.net and yektablog.net breakage

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#20]
Example: [takblog.net](https://takblog.net) and [yektablog.net](https://yektablog.net)

Fix: 
```
takblog.net,yektablog.net###popbox-blackout
takblog.net,yektablog.net###popbox-close
```

Reason:
![image](https://user-images.githubusercontent.com/17685483/145770617-068deba1-e08a-4679-b3ef-82bd63bf0812.png)

Broken:
![image](https://user-images.githubusercontent.com/17685483/145770723-218d51a0-b79c-49dd-8ddc-3a1548474a76.png)

Fixed:
![image](https://user-images.githubusercontent.com/17685483/145770743-28f05d0e-751b-41c2-848b-e476237d53f9.png)

**Comment by nimasaj** [comment]
Thanks for reporting the issue. It's fixed on https://github.com/nimasaj/uBOPa/commit/d5228fb9a5e193435a07c79d11b95fe93ea46a93.
