### ISSUE TITLE
blogfa.com breakage (?)

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#21]
Example: [blogfa.com](blogfa.com)
The "تبلیغات در وبلاگها" shouldn't be blocked because it's not ads, it's just an article _about_ ads.

* Reason:
`*##a[href$="/ads"]`
![image](https://user-images.githubusercontent.com/17685483/146004560-f8bae36b-4c94-4088-8803-24d895f14182.png)

* Broken:
![image](https://user-images.githubusercontent.com/17685483/146004310-03da98de-8e13-4a43-b8cc-c6c8eab07e7c.png)

* Fixed:
![image](https://user-images.githubusercontent.com/17685483/146004280-5233f011-3fea-43ff-8685-5778e4c05e9f.png)

**Comment by nimasaj** [comment]
Thanks for reporting the issue. It's fixed now on https://github.com/nimasaj/uBOPa/commit/b17b4e3ffe10560dd7d8f9a25a984eb8490b099d.
