### ISSUE TITLE
blogfa.com breakage

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#22]
The `||ashoora.*` filter from your list causes complete breakage on [eternaliran.blogfa.com](https://eternaliran.blogfa.com) by blocking ashoora.biz and ashoora.ir.
How did this site end up on your filterlist anyway? It doesn't seem to show ads.

* Possible solution:
`@@||ashoora.*$domain=blogfa.com` or just remove the filter from your list

* Reason:
![image](https://user-images.githubusercontent.com/17685483/146150363-7282cfd6-181b-43fe-bb26-f7e369317672.png)

![image](https://user-images.githubusercontent.com/17685483/146150332-6ed37b8b-9984-4f49-ae6c-3714fadff922.png)

![image](https://user-images.githubusercontent.com/17685483/146153514-7b7d9da2-020c-4cb1-8db2-769cca16b241.png)

**Comment by nimasaj** [comment]
Thanks for reporting. It's now fixed on https://github.com/nimasaj/uBOPa/commit/7a01860a857c6a687ab2ce249f2b5659b81d3067.
