### ISSUE TITLE
ashoora.ir breakage

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#23]
These filters from your list cause complete breakage on ashoora.ir:
```
||ashoora.*
*##*[class^="banner1"]
*##*[class^="banner2"]
*##img[src*="/banners/"]
*##a[href*="/banners/click/"]>img
```

* Solution:

```
@@||ashoora.ir (or just remove ||ashoora.* from your list)
ashoora.ir#@#*[class^="banner1"]
ashoora.ir#@#*[class^="banner2"]
ashoora.ir#@#img[src*="/banners/"]
ashoora.ir#@#a[href*="/banners/click/"]>img
```

![image](https://user-images.githubusercontent.com/17685483/146152639-be8fa764-a65e-4322-acf3-c9294e548ec2.png)

![image](https://user-images.githubusercontent.com/17685483/146153387-92cfb35b-8171-4552-9a05-d77c55188864.png)

**Comment by nimasaj** [comment]
Thanks for reporting. It's now fixed on https://github.com/nimasaj/uBOPa/commit/7a01860a857c6a687ab2ce249f2b5659b81d3067.

**Comment by nimasaj** [comment]
The filters were removed in https://github.com/nimasaj/uBOPa/commit/b796c46e03edb8a4b636eec568aa1e14d438a281 since there is no support for websites that are promoting violence, ignorance, terrorism and Islam.

**Comment by MasterKia** [comment]
I wonder how they were added in the first place.
