### ISSUE TITLE
unbreak code for integromat.com

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#25]
Similar to https://github.com/nimasaj/uBOPa/issues/11

![image](https://user-images.githubusercontent.com/17685483/146356699-01a7127c-7d51-433b-86bf-d7ff246a89c3.png)

The `*/ads.*` filter on your list is triggering the anti-adblock on integromat.com by blocking this script:
`https://static.integromat.com/js/ads.js`

Example:
`https://www.integromat.com/en/integrations/discord/telegram`

* Suggested Solution:
`integromat.com##+js(set, imt.adblock, false)`

* Another solution:
`@@||static.integromat.com/js/ads.js$script,domain=integromat.com`

**Comment by nimasaj** [comment]
Thanks for reporting. It's now fixed on https://github.com/nimasaj/uBOPa/commit/7a01860a857c6a687ab2ce249f2b5659b81d3067.
