### ISSUE TITLE
uupload.ir timer

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#26]
* Example: `https://uupload.ir/view/l8qz_%D9%82%D8%A7%D9%84%D8%A8_%D8%B3%D8%A7%D8%AF%D9%87_%D8%B2%D9%85%D8%B3%D8%AA%D8%A7%D9%86_%D8%A8%D9%84%D8%A7%DA%AF%D9%81%D8%A7.txt`

* Solution: `uupload.ir##+js(nano-sib)`

**Comment by nimasaj** [comment]
Thanks for reporting. It's now fixed on https://github.com/nimasaj/uBOPa/commit/7a01860a857c6a687ab2ce249f2b5659b81d3067.
