### ISSUE TITLE
dontasktoask.ir breakage

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#27]
This filter `*##a[href*="utm_medium=banner"]` from your list causes this issue on [dontasktoask.ir](https://dontasktoask.ir).

Solution: `dontasktoask.ir#@#a[href*="utm_medium=banner"]`

Go to the bottom of the page.
* Broken:
![image](https://user-images.githubusercontent.com/17685483/146634970-eed6dd59-762f-4a84-937c-c432050b00bc.png)

* Fixed:
![image](https://user-images.githubusercontent.com/17685483/146634945-c839dd33-825c-4a2a-a5a8-1e5bc758cfd6.png)

**Comment by nimasaj** [comment]
Thanks for reporting the issue. It's now fixed on https://github.com/nimasaj/uBOPa/commit/7a01860a857c6a687ab2ce249f2b5659b81d3067.
