### ISSUE TITLE
makeuseof.com breakage

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#28]
These filter from your list break `https://www.makeuseof.com/advertise/`:
```
*##a[href*="utm_medium=affiliate"]
*##*[class^="advert"]
*##*[class*=" adv-"]
*-ads.*$domain=~aparat.com|~varzesh3.com
```

* Solution:
```
makeuseof.com#@#a[href*="utm_medium=affiliate"]
makeuseof.com#@#*[class^="advert"]
makeuseof.com#@#*[class*=" adv-"]
@@||makeuseof.com/public/build/images/banner-ads.*.png$image,domain=makeuseof.com
```

![image](https://user-images.githubusercontent.com/17685483/146664476-7b04c8eb-2833-46c9-9efe-316204b1d144.png)
![image](https://user-images.githubusercontent.com/17685483/146664498-34998156-45c9-4d66-9866-0a1fb4ba6c72.png)

* Broken:
![image](https://user-images.githubusercontent.com/17685483/146664483-dd635e8b-a69e-43bf-91ae-70b8150d54be.png)

* Fixed:
![image](https://user-images.githubusercontent.com/17685483/146664494-1621b081-f19b-4948-94cc-33653df13ec4.png)

**Comment by MasterKia** [comment]
This isn't fully addressed in the latest commit.

**Comment by nimasaj** [comment]
Thanks for reporting. It's fixed now on https://github.com/nimasaj/uBOPa/commit/a44612069105ed574eb2cc43e4aedf82c8bd28dc.

**Comment by nimasaj** [comment]
Revised on https://github.com/nimasaj/uBOPa/commit/861b5067a96804b8c3dce02b596ac65f18a0afab.
