### ISSUE TITLE
wrong filter

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#29]
The `/banner/*.gif` filter from your list, blocks `hassamaldin.blogfa.com` on `https://hassamaldin.blogfa.com`.

I think the filter is unnecessary because it has the potential to block a lot of things so please remove it, if you see fit.

**Comment by nimasaj** [comment]
Thanks for reporting the issue. It's now fixed on https://github.com/nimasaj/uBOPa/commit/7a01860a857c6a687ab2ce249f2b5659b81d3067.
