### ISSUE TITLE
Removed download links from Microsoft Website

### ISSUE THREAD

**Issue by msasanmh** [nimasaj/uBOPa#3]
Hi, your list will block the main content from below link:
[https://www.microsoft.com/en-us/download/details.aspx?id=48145](https://www.microsoft.com/en-us/download/details.aspx?id=48145)
this is the official page for downloading C++ 2015 Runtime.
Please don't be aggressive when writing generic filters.

**Comment by nimasaj** [comment]
@msasanmh,
Thanks for reporting. The issue is fixed. Please update your list.
