### ISSUE TITLE
unbreak code for cpubenchmark.net

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#30]
Similar to: https://github.com/nimasaj/uBOPa/issues/11

`https://www.cpubenchmark.net/js/ads.js`:
`var canRunAds = true;`
Solution:
`cpubenchmark.net##+js(set, canRunAds, true)` or `@@||cpubenchmark.net/js/ads.js$script,domain=cpubenchmark.net`

![image](https://user-images.githubusercontent.com/17685483/146915985-59814c8e-eebb-4386-aee4-e213153aac08.png)

![image](https://user-images.githubusercontent.com/17685483/146916139-acdad730-b67f-4afc-857d-a5ad8ff457dd.png)

**Comment by nimasaj** [comment]
Thanks for reporting the issue. It's now addressed on https://github.com/nimasaj/uBOPa/commit/7a01860a857c6a687ab2ce249f2b5659b81d3067.
