### ISSUE TITLE
hamtamovie.bar and s0ft98.ir timer

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#31]
hamtamovie.bar example:
`https://hamtamovie.bar/dl/?url=https://cld7.hostdl.net/serial/foreign/2020/money-heist/Money_Heist_S01_E01_1080p.mkv`

s0ft98.ir example (Replace 0 with o):
`https://linkdoni.s0ft98.ir/link-25022.html` 

* Solution:
```
hamtamovie.bar##+js(nano-stb)
linkdoni.s0ft98.ir##+js(nano-stb) (Replace 0 with o)
```

**Comment by nimasaj** [comment]
Thanks for reporting and the suggestions. It's addressed now on https://github.com/nimasaj/uBOPa/commit/a44612069105ed574eb2cc43e4aedf82c8bd28dc.
