### ISSUE TITLE
windowscentral.com breakage

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#32]
* Reason: `*##*[class*="-ads "]` and the site is completely blank.

* Solution: `windowscentral.com#@#*[class*="-ads "]`

* Example: `https://www.windowscentral.com/how-disable-touchpad-while-mouse-connected-windows-10`

![image](https://user-images.githubusercontent.com/17685483/147526198-8f0a2a0f-27c8-424a-b666-9e0f64ad605e.png)

**Comment by nimasaj** [comment]
Thanks for reporting the issue. It's fixed now on https://github.com/nimasaj/uBOPa/commit/b5970a1565f962a6668aea38d890740e6708186e.
