### ISSUE TITLE
wikifeqh.ir breakage

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#33]
* Reason:
`*##*[id*="topbanner"]`

* Solution:
`wikifeqh.ir#@#*[id*="topbanner"]`

* Example:
`https://fa.wikifeqh.ir/%D8%A7%D8%B3%D8%A7%D9%85%DB%8C%20%D8%B3%D9%88%D8%B1%D9%87%20%D8%AA%D9%88%D8%A8%D9%87`

![image](https://user-images.githubusercontent.com/17685483/147643175-a6dd9f2d-5dd3-451c-a894-f98a17d5c178.png)

![image](https://user-images.githubusercontent.com/17685483/147643184-c6fb1007-2ff5-4ae6-81c1-ea4780233a8c.png)

![image](https://user-images.githubusercontent.com/17685483/147643208-4eaf8013-6225-4942-b2d4-f37ea066a254.png)

**Comment by nimasaj** [comment]
Sorry. There is no support for websites that are promoting violence, ignorance, terrorism and Islam.
