### ISSUE TITLE
khf.nz wrong filter

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#34]
* Reason:
`*_banner*$domain=~utah.edu|~cable.co.uk|~grammarly.com`

* Solution:
`*_banner*$domain=~utah.edu|~cable.co.uk|~grammarly.com|~khf.nz` or `@@||*.khf.nz/sites/default/files/upload_banner/*$image` (or just remove the filter from your list)

* Example:
`https://postman.blogfa.com`
`https://s1.khf.nz/sites/default/files/upload_banner/02_78.jpg`

![image](https://user-images.githubusercontent.com/17685483/147650196-71a7ac71-cfa0-4c3e-8765-1a7aa6dae33b.png)

![image](https://user-images.githubusercontent.com/17685483/147650204-7e4e4a67-5c6e-4642-8192-696d011692a1.png)

**Comment by nimasaj** [comment]
Thanks for reporting the issue. The website was not loaded on my side. Please make sure if the added rule at https://github.com/nimasaj/uBOPa/commit/b796c46e03edb8a4b636eec568aa1e14d438a281 works for you.

**Comment by MasterKia** [comment]
https://github.com/nimasaj/uBOPa/commit/b796c46e03edb8a4b636eec568aa1e14d438a281#r62710330

**Comment by nimasaj** [comment]
The whole domain is whitelisted, https://github.com/nimasaj/uBOPa/commit/914c41bc782a13dd4c42cc0dbe8b0525ceaa9f8e. 

For the record:
Khf.nz is affiliated with `https://khabarfarsi.com/` which is kind of a news portal.

**Comment by MasterKia** [comment]
Even though you explicitly whitelisted `khf.nz` in the latest commit, it doesn't seem to work; is something wrong on my end?
You can visit `https://postman.blogfa.com/` and check the logger.

![image](https://user-images.githubusercontent.com/17685483/147821510-3cae718c-fe91-4c1d-af83-d1e2f785dcf2.png)

![image](https://user-images.githubusercontent.com/17685483/147821519-3469e53f-f418-4c00-b39c-8ce8c9ba7130.png)

**Comment by nimasaj** [comment]
Please make sure if the commit https://github.com/nimasaj/uBOPa/commit/3a1295640da28b587f05386b9fc5146b26f09db9 works on your side.

**Comment by MasterKia** [comment]
> Please make sure if the commit [3a12956](https://github.com/nimasaj/uBOPa/commit/3a1295640da28b587f05386b9fc5146b26f09db9) works on your side.

Seems to work.
![image](https://user-images.githubusercontent.com/17685483/147822407-2c100cea-22d1-4464-ae43-a7202db8e121.png)
