### ISSUE TITLE
eghtesadonline.com ads

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#35]
* Proposed filters:
```
eghtesadonline.com##.desktop-banner.noprint.talfighat-View
eghtesadonline.com##.right.clone.position-g3.type-resource-mp4.type-resource
eghtesadonline.com##div.lslide.position-g3.type-resource-mp4.type-resource
eghtesadonline.com##.usingCss.lSSlideWrapper
```
* Before:
![image](https://user-images.githubusercontent.com/17685483/147744127-33d9199e-51a7-470e-8b6c-182e9bc90858.png)

* After:
![image](https://user-images.githubusercontent.com/17685483/147744364-90c32fa5-3ef7-4c6b-bcd9-28853a545928.png)

**Comment by nimasaj** [comment]
Thanks for reporting the issue. It's fixed now at https://github.com/nimasaj/uBOPa/commit/d15e230f0248a434efccc1146de68e324320e6ab.
