### ISSUE TITLE
yun.ir ads

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#36]
`yun.ir##.advertisements.container.ui`

![image](https://user-images.githubusercontent.com/17685483/147793081-c05426b6-b787-4d78-b0f3-c7991d0bc2d5.png)

**Comment by nimasaj** [comment]
Thanks for reporting the issue. It's fixed in https://github.com/nimasaj/uBOPa/commit/0c3fd76fdf90217e0d6945d3223114f2d4f9be13.
