### ISSUE TITLE
iwo.ir timer

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#37]
Example: `http://iwo.ir/os1nw`

Solution: `iwo.ir##+js(nano-sib)`

![image](https://user-images.githubusercontent.com/17685483/147793139-68ffee03-90ed-4fa1-841f-0a9677d3ec1c.png)

**Comment by nimasaj** [comment]
Thanks for reporting the case and also the suggestion. It's added in https://github.com/nimasaj/uBOPa/commit/0c3fd76fdf90217e0d6945d3223114f2d4f9be13.
