### ISSUE TITLE
marzfun.com ads

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#38]
Example: `https://www.marzfun.com/banshee-serial.html`

The "تبلیغات" and "تبلیغات متنی" should be blocked: 

![image](https://user-images.githubusercontent.com/17685483/147807568-ef24a20c-0763-4f77-9d50-2648e7d03b5d.png)

**Comment by nimasaj** [comment]
Thanks for reporting the case. It's fixed in https://github.com/nimasaj/uBOPa/commit/914c41bc782a13dd4c42cc0dbe8b0525ceaa9f8e.
