### ISSUE TITLE
pintermusic.ir popup

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#39]
Go to `https://pintermusic.ir` and click anywhere on the page.
A popup from `https://cofeappleid.ir` opens up at the _bottom right corner of the screen_.

This `pintermusic.ir##+js(window.open-defuser)` filter seems to fix the issue but there might be a better way.

This section in site's code might be related to the popup:
```
<script type="text/javascript" language="javascript" src="https://pintermusic.ir/copu2.js"></script>
<p>فروش انواع اپل آیدی از فروشگاه کافه اپل آیدی با آدرس https://cofeappleid.ir</p></div></div>
```

**Comment by nimasaj** [comment]
Thanks for reporting the case. It's fixed now in https://github.com/nimasaj/uBOPa/commit/c45b033732147d83ab772bd0d76517a249037945.

**Comment by MasterKia** [comment]
It doesn't work.
