### ISSUE TITLE
False positive report

### ISSUE THREAD

**Issue by DRSDavidSoft** [nimasaj/uBOPa#4]
Hi there,

It seems that this line ↓ is interfering with a link on the following page:
https://github.com/nimasaj/uBOPa/blob/6bd88a1069917b6898643d48e6d1040b84b5b56e/uBOPa.txt#L1748

- https://blocklist.site/app/list-details.php?list=ads
   the link in the qiestion is `https://blocklist.site/app/dl/ads`, under the download section.

Could you please append an exception rule for the `blocklist.site` links?

**Comment by nimasaj** [comment]
Thanks for reporting. It is fixed now. Please update the list.
