### ISSUE TITLE
mihandownload.com ads banner

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#40]
Solution: `mihandownload.com##.alert-new`

![image](https://user-images.githubusercontent.com/17685483/147844687-18d5a1d9-7ac2-4810-9824-ea12317cfa6a.png)

**Comment by nimasaj** [comment]
Thanks for reporting it. It's fixed now in https://github.com/nimasaj/uBOPa/commit/c08dca1de30032c9259e22eeee928feda2e0ce37.
