### ISSUE TITLE
downloadmusic.ir ads

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#41]
* Example: `https://download1music.ir/song-without-words/`

* Solution:
```
download1music.ir###pos-article-display-12392
download1music.ir##.wp-image-96250.size-full.aligncenter 

(I think there would be a better filter that doesn't rely on numbers like 12392 and 96250)
```

* Before:
![image](https://user-images.githubusercontent.com/17685483/147899087-d73e2096-9e8c-4915-bee4-ec9c0d3ef003.png)

* After:
![image](https://user-images.githubusercontent.com/17685483/147899261-41cb6e58-dc2c-4e25-b5bd-3f689bb18b2c.png)

**Comment by nimasaj** [comment]
Thanks for reporting the case. It's fixed now in https://github.com/nimasaj/uBOPa/commit/f35c351ba746bbfdd87e91ced3c85a517d977c2c. I hope it doesn't break any other part of the website. I had a quick look and it seemed fine, but I didn't investigate thoroughly. If there was a problem with the filters, please report them to get fixed.
