### ISSUE TITLE
pop-music.ir breakage

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#42]
The "**Special Musics**" section is blocked.

* Example: `https://pop-music.ir`

* Reason:
`*##*[class^="ads-"]`

![image](https://user-images.githubusercontent.com/17685483/147974162-b4d357e5-feb2-400b-b825-e37e730df55e.png)

* Solution:
`pop-music.ir#@#*[class^="ads-"]`

* Before:
![image](https://user-images.githubusercontent.com/17685483/147974189-2f672d42-00ae-4937-987d-a48eca7744ce.png)

* After:
![image](https://user-images.githubusercontent.com/17685483/147974531-225e7385-a596-4b4a-8181-56361f6b366f.png)

**Comment by nimasaj** [comment]
Thanks for the report. It's fixed in https://github.com/nimasaj/uBOPa/commit/3a32654a98feb8b5dd4ac6f43e55d5aab8fbe0e1.
