### ISSUE TITLE
uploadboy.com ads

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#43]
* Example (Scroll to the bottom): `http://uploadboy.com/feimrftp1t5l`
* Proposed filter:
`||uploadboy.com/images/asiatech$image`

![image](https://user-images.githubusercontent.com/17685483/148334586-2c14e554-d044-4bc6-a73b-8faaabaeae19.png)

**Comment by nimasaj** [comment]
I cannot reproduce the issue. Could you please provide source of the page where the image is mentioned in? Maybe I can come up with a wider filter that blocks not only Asiatech but other future advertisers as well.

**Comment by MasterKia** [comment]
> source of the page where the image is mentioned in



> * Example (Scroll to the bottom): `http://uploadboy.com/feimrftp1t5l`

Isn't this helping?

**Comment by MasterKia** [comment]
It appears that `uploadboy.com` has different versions for each language and the _asiatech_ ads **only** appear if you're visiting from Iran.

```
            <div class="col-md-12" style="text-align:center;">
               <a target="_blank" rel="nofollow"  href="http://www.asiatech.ir/" >
<img width="300" height="100" src="//uploadboy.com/images/asiatech300-100.gif" border="0"></a>
            </div>
```

* Source code (Iran IP):
Find "asia" => 2 results
![image](https://user-images.githubusercontent.com/17685483/148458408-69a7f802-21f4-4c91-a77f-89a5c944d7c6.png)


* Source code (non-Iran IP):
Find "asia" => 0 results
![image](https://user-images.githubusercontent.com/17685483/148458287-718513f0-b72b-4141-b8ca-4dce8ea5c299.png)

**Comment by MasterKia** [comment]
> It appears that `uploadboy.com` has **_different_** versions for each language

Also that explains the _odd behavior_ on this previously solved [issue](https://github.com/nimasaj/uBOPa/issues/18#issuecomment-990922684) with regards to the timer and the litebox banner.

**Comment by nimasaj** [comment]
No. I guess the ads are geo-targeted and I cannot see that ad in my side. Please provide me source of the page.

**Comment by MasterKia** [comment]
> No. I guess the ads are geo-targeted and I cannot see that ad in my side. Please provide me source of the page.

https://github.com/nimasaj/uBOPa/issues/43#issuecomment-1006966685

**Comment by nimasaj** [comment]
Thanks for the report. Please check out the commit https://github.com/nimasaj/uBOPa/commit/3a32654a98feb8b5dd4ac6f43e55d5aab8fbe0e1 if it works for you.
