### ISSUE TITLE
bravotv.com breakage

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#44]
* Example: `https://www.bravotv.com/the-real-housewives-of-orange-county/season-16/episode-1/fancy-pants-is-back`
The site is completely blank.

* Reason:
![image](https://user-images.githubusercontent.com/17685483/148506183-82ea31f9-c171-4d9a-af2f-36b90b3c7a0d.png)

* Solution:
`bravotv.com#@#*[class$="-ad"]`

Are generic cosmetic filters a good idea in your opinion?

**Comment by nimasaj** [comment]
Thanks for the report. It's fixed in https://github.com/nimasaj/uBOPa/commit/3a32654a98feb8b5dd4ac6f43e55d5aab8fbe0e1.
