### ISSUE TITLE
gadgets.usanewstoday.club detection

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#45]
Similar to:
https://github.com/nimasaj/uBOPa/issues/11
https://github.com/nimasaj/uBOPa/issues/25
https://github.com/nimasaj/uBOPa/issues/30

The generic filters are often causing issues recently.

* Example: `https://gadgets.usanewstoday.club/JbRq`

* Reason:
```
*##*[id^="ad-"]
/ads.$domain=~filecr.com
```

* Solution:
```
@@||gadgets.usanewstoday.club/js/ads.js
gadgets.usanewstoday.club#@#*[id^="ad-"]
```

![image](https://user-images.githubusercontent.com/17685483/148509294-1feded95-b864-4cba-8216-fd9980f6a70e.png)

![image](https://user-images.githubusercontent.com/17685483/148509340-3c008044-3bfb-44ea-af11-ffbe28494b52.png)

![image](https://user-images.githubusercontent.com/17685483/148509193-efd9ff4e-20f8-4bfe-8dba-c9a2540de223.png)

**Comment by nimasaj** [comment]
Thanks for the report. It's fixed in https://github.com/nimasaj/uBOPa/commit/3a32654a98feb8b5dd4ac6f43e55d5aab8fbe0e1.
