### ISSUE TITLE
enbdev.com detection

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#46]
Similar to:
https://github.com/nimasaj/uBOPa/issues/11
https://github.com/nimasaj/uBOPa/issues/25
https://github.com/nimasaj/uBOPa/issues/30
https://github.com/nimasaj/uBOPa/issues/45

* Example: `http://enbdev.com/download_mod_gta4.htm`

* Reason: 
`*_ads.*`

* Solution:
`enbdev.com##+js(set, isexistAd, true)` or `@@||enbdev.com/_google_ads.js$script,1p`

![image](https://user-images.githubusercontent.com/17685483/148511059-7cc4669c-3339-4226-8e1b-f3edcc6584ed.png)

![image](https://user-images.githubusercontent.com/17685483/148511211-0875eea7-1424-4b49-bb72-f4806cdec69a.png)

**Comment by nimasaj** [comment]
Thanks for the report and the solution. It's fixed in https://github.com/nimasaj/uBOPa/commit/3a32654a98feb8b5dd4ac6f43e55d5aab8fbe0e1.
