### ISSUE TITLE
cheatsquad.gg detection

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#47]
* Example: `https://cheatsquad.gg`

If I disable the **uBOPa list** or use `@@||cheatsquad.gg^$generichide`, then the anti-adblock warning is gone.

![image](https://user-images.githubusercontent.com/17685483/148512380-928044a0-b90b-4631-b8d2-bec9b718b2a4.png)

**Comment by nimasaj** [comment]
Thanks for reporting the issue. It's fixed now in https://github.com/nimasaj/uBOPa/commit/a78f136f0b663dc7088122a3ca95568a159ac1d0.
