### ISSUE TITLE
toolzu.com breakage

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#48]
### They're causing too much issues.

* Example: `https://toolzu.com/downloader/instagram/stories/`

* Reason: `*##*[class$="-ad"]`
![image](https://user-images.githubusercontent.com/17685483/149008136-c48e9f43-51d7-4475-b4eb-920a15a4f1d1.png)

* Solution: `toolzu.com#@#*[class$="-ad"]`

* Broken:
![image](https://user-images.githubusercontent.com/17685483/149008087-5bd04815-2a4d-464e-a14d-ec860b72b3db.png)

* Fixed:
![image](https://user-images.githubusercontent.com/17685483/149008192-41991f8f-d73b-4925-b5a4-5522f1f7cf74.png)

**Comment by nimasaj** [comment]
Thanks for the report. It's fixed in https://github.com/nimasaj/uBOPa/commit/3a32654a98feb8b5dd4ac6f43e55d5aab8fbe0e1.
