### ISSUE TITLE
dns راهی برای تولید    

### ISSUE THREAD

**Issue by net-warriors** [nimasaj/uBOPa#49]
سلام خسته نباشید واقعا بابت زحماتتون ممنونیم 
یه نکته ای که خیلی واسم با ارزش بود و ازتون کمک خواستم این هستش که فردی مثل شما داره در مورد حذف تبلیغات کار میکنه و سورسی رو توی گیت هاب منتشر کرده ک بنظر بنده خیلی با ارزش میاد . 
یک dns که هم از نوع ipv4   ipv6   DOH  DOT هستش و میشه توی مودم و... استفاده کرد با وجود اینکه من از ادگارد استفاده کردم اما به اندازه این dns نتیجه نگرفتم و این دی ان اس رو خیلی بهتر از ادگارد نسخه ipv4 میدونم به خاطر همین باهاش صحبت کردم که تبلیغات زبان فارسی رو به تبلیغاتش اضافه کنه اما نمیشد از منابع شما استفاده کرد خواستم بگم باهاشون ارتباط بگیرید شاید بشه راهی برای ساخت dns قوی و بدرد بخور ساخت لطفا باهاش ارتباط بگیرید 
از طرف همه بچه ها ازتون خیلی ممنونیم

https://github.com/ragibkl/adblock-dns-server

**Comment by nimasaj** [comment]
درود و مرسی از پیامت.
لیست uBOPa براساس افزونه ی uBlock Origin توسعه داده شده است. این افزونه درخواست های وب را در لایه ی مرورگر و براساس موتور مرورگر بررسی میکند و تغییرات لازم را میدهد که شامل تغییرات ظاهری (المان های ظاهری صفحه) و بستن درخواست های TCP/IP مرورگر است. همچنین امکان تزریق کدهای جاوا-اسکریپت برای دستکاری در اسکریپت های اجرا شده در سمت کاربر را دارد.
موردی که شما درخواستش را دادی براساس درخواست های سخت افزاری زیرساخت شبکه است و در این لایه چندان امکان مانور دادن وجود ندارد، به همین دلیل از راه بستن IP از سمت DNS اقدام میشود.
و زمانی که موضوع بستن IP است، دیگر شما امکان بستن فقط یک پوشه (فولدر) بر روی سرور را ندارید و به همین دلیل لیست نهایی هم کوچکتر میشود و هم محدودتر. 
تنها نسخه ای از لیست uBOPa که سازگاری با روش های بستن در سمت سخت افزار را دارد نسخه ی pi hole است که از [اینجا](https://mynext.pro/uBOPa_Pihole.txt) و یا [اینجا](https://raw.githubusercontent.com/nimasaj/uBOPa/master/uBOPa_Pihole.txt) در دسترس است.
