### ISSUE TITLE
Problem with Microsoft website

### ISSUE THREAD

**Issue by fakhamatia** [nimasaj/uBOPa#5]
![Screenshot from 2019-11-09 18-38-26](https://user-images.githubusercontent.com/20030910/68530722-51892280-0320-11ea-86de-574809227dc2.png)

**Comment by nimasaj** [comment]
@fakhamatia ,

Thank you for reporting. Fixed in https://github.com/nimasaj/uBOPa/commit/a25f0d39c90555621573c057bfa8f6fd0a68ace0
