### ISSUE TITLE
yjc.news false block

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#51]
Example: `https://www.yjc.news/fa/news/7115908/%D8%B1%D9%88%D8%B4-%D8%AB%D8%A8%D8%AA-%D8%AA%D9%84%D9%81%D9%86-%D8%A8%D8%B1%D8%A7%DB%8C-%D8%AF%D8%B1%DB%8C%D8%A7%D9%81%D8%AA-%D9%82%D8%A8%D8%B6-%DA%AF%D8%A7%D8%B2-%D8%AE%D8%AF%D8%A7%D8%AD%D8%A7%D9%81%D8%B8%DB%8C-%D8%A8%D8%A7-%D9%82%D8%A8%D9%88%D8%B6-%DA%A9%D8%A7%D8%BA%D8%B0%DB%8C-%D8%A7%D8%B2-%D8%A2%D8%B0%D8%B1-%D8%A7%D9%85%D8%B3%D8%A7%D9%84`

Reason: `/adv/*`

![image](https://user-images.githubusercontent.com/17685483/158224036-b6b28bc0-239d-44f1-8e08-3096ed435809.png)

`https://cdn.yjc.news/files/adv/4070_785.jpg` :
![image](https://user-images.githubusercontent.com/17685483/158224109-0c2e7a0a-1f5f-45ba-908f-6fa2a5655829.png)

**Comment by nimasaj** [comment]
Thanks for the report. It's now fixed in https://github.com/nimasaj/uBOPa/commit/b7cd461f175a165952f240b9a328555cb455746d and https://github.com/nimasaj/uBOPa/commit/e300d2ebab89c2c71981c52bea3b3837d1986538.
