### ISSUE TITLE
alaatv.com pre-roll ads and banner

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#52]
* Example: `https://alaatv.com/c/30756`

* Solution for pre-roll ads:
`alaatv.com##+js(set, vastData, null)`

* Solution for the banner (خرید اشتراک تلسکوپ):
`alaatv.com##.fading-watermark-text`

* Screenshots:
![image](https://user-images.githubusercontent.com/17685483/158565411-b9bd4bc1-8ae6-4a8d-9401-46b922a5f61b.png)

![image](https://user-images.githubusercontent.com/17685483/158565421-537d6772-c8f4-4357-8ce4-de3f370c8498.png)

![image](https://user-images.githubusercontent.com/17685483/158565606-766d7568-11bf-4e29-939c-6035e1e215a6.png)

**Comment by nimasaj** [comment]
Thanks for the report. Please check if https://github.com/nimasaj/uBOPa/commit/a27714afb5ed1a24f34f94fa57dd46fc02992139 works for you.

**Comment by MasterKia** [comment]
> Please check if [a27714a](https://github.com/nimasaj/uBOPa/commit/a27714afb5ed1a24f34f94fa57dd46fc02992139) works for you.

It seems to work but it causes an empty space, I don't know why that happens I think no functionality is broken.

* Without your filter:
![image](https://user-images.githubusercontent.com/17685483/158641332-3c89526a-7124-4c8f-81a7-d53bac281cb7.png)


* With your filter:
![image](https://user-images.githubusercontent.com/17685483/158641265-7f2d43c8-7d43-4c0d-9521-98a5943aba12.png)

**Comment by nimasaj** [comment]
It has nothing to do with the filter rule. The page is responsive to screen size. If you make your browser window smaller or bigger, or load the page on a different screen size, that empty space will be gone or visible as shown in the following images.
With uBO on (including the filter) | 2560x1440 screen resolution, `https://pasteboard.co/ABupbT119aPP.png`
With uBO off | 1380x1202 screen resolution, `https://pasteboard.co/LwlF8V0VDq9Q.png`

**Comment by MasterKia** [comment]
> It has nothing to do with the filter rule.

For me when uBOPA list is disabled the empty space is removed but when uBOPA list is enabled the empty space is present.

**Comment by MasterKia** [comment]
I guess we will see if it affects any functionality or causes any breakage.
