### ISSUE TITLE
osdn.net breakage

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#54]
* Example: `https://osdn.net/projects/android-x86/releases`

* Reason: `*##*[class$="_ads"]`
![image](https://user-images.githubusercontent.com/17685483/158583684-5d5c9d57-1fc0-45e8-8749-8b03d26a5f83.png)

* Solution: `osdn.net#@#*[class$="_ads"]`

tbh these generic rules tend to break websites a lot.

**Comment by nimasaj** [comment]
Thanks for the report. It's fixed in https://github.com/nimasaj/uBOPa/commit/a27714afb5ed1a24f34f94fa57dd46fc02992139.
The generic rules have pros and cons at the same time. If there are too many false positives, I will either make it specific, or remove it.
