### ISSUE TITLE
thebalancecareers.com breakage

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#55]
Example: `https://www.thebalancecareers.com/how-to-end-a-letter-2062308`

Broken: ![image](https://user-images.githubusercontent.com/17685483/166253843-c7949ac4-c8ee-41a1-bb5a-faf320d54677.png)
Fixed: ![image](https://user-images.githubusercontent.com/17685483/166253871-bdb63d4b-2c0b-4208-9d7e-f9b0ff5747cb.png)

![image](https://user-images.githubusercontent.com/17685483/166254287-3d3d5934-f622-41c5-8fae-17b8a58cd3e4.png)

Solution: `thebalancecareers.com#@#*[class*="-ad-container"]`

I think the cosmetic filters are **too broad** and a different approach must be taken.

**Comment by nimasaj** [comment]
Thanks for the report. It's fixed now in https://github.com/nimasaj/uBOPa/commit/1632b2dfebb69e341c1765934092a871717449ae
