### ISSUE TITLE
article.tebyan.net ads

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#57]
Example: `https://article.tebyan.net/306262/%D8%AD%D8%A7%D9%84%D8%A7-%D8%A7%DA%AF%D8%B1-%D9%85%DB%8C-%D8%AE%D9%88%D8%A7%D9%87%DB%8C%D8%AF-%D9%BE%D9%81%DA%A9-%D8%A8%D8%AE%D9%88%D8%B1%DB%8C%D8%AF`

The top banner is ads and needs to be blocked.
The bottom banner is self-promotion and doesn't need to be blocked.
![image](https://user-images.githubusercontent.com/17685483/169345868-50dbaef2-9c99-4913-b93f-0a467bdccef5.png)

**Comment by nimasaj** [comment]
Thanks for the report. As it could be seen through the website, it's promoting "Terrorism" & "Islam" and as a result it's not supported.

**Comment by MasterKia** [comment]
> Thanks for the report. As it could be seen through the website, it's promoting "Terrorism" & "Islam" and as a result it's not supported.

Well those were ads.

Who's to say someone doesn't submit an ads like that to YouTube or Google AdSense tomorrow?

**Comment by nimasaj** [comment]
That banner ad is loaded from that website (Tebyan) and is specific to the website. If anything should be done about it, it's an element-hiding rule, specific to the website.  
The  no-support for websites that are promoting terrorism and Islam applies to websites, not the ads. If the ad was loaded from a 3d party or an advertising company, it'd be added to the list.
