### ISSUE TITLE
New list: PersianBlocker

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#58]
I've rewritten the [Adblock-Iran](https://github.com/farrokhi/adblock-iran) and created a new efficient and extensive list: [PersianBlocker](https://github.com/MasterKia/PersianBlocker).

Today the PersianBlocker list has been [added](https://github.com/gorhill/uBlock/commit/33b839fdd03f74689df3ee2b5c25a06435b350e0) to uBlock Origin's regional list.
I'm planning on bringing new sites/filters from Adblock Farsi and uBOPa into the PersianBlocker list to increase it's coverage and usefulness.

I've added your list in the [credits](https://github.com/MasterKia/PersianBlocker#%DA%AF%D8%B1%D8%A7%D9%85%DB%8C%D8%AF%D8%A7%D8%B4%D8%AA) section and I'm willing to cooperate with you on this new list.

**Comment by nimasaj** [comment]
Congrats. Keep developing and make your list efficient. As you may know, Google is working on manifest v3 and it could impact all ad blockers and list maintainers to keep their list short. Hopefully it doesn't happen at all or anytime soon, otherwise, many lists will become obsolete and list maintainers will be forced to use more generic filters in the future to reduce the size. Be ready for such move.

**Comment by MasterKia** [comment]
Yeah unfortunately that's what happen when an advertising company (Google) develops a browser.
So far I've seen major browsers like Brave and Vivaldi stating that they won't remove manifest v2.
And IIRC Microsoft said the same thing about Edge (but I think I'm wrong).

Chrome users will certainly be unhappy about this, but they could migrate to Firefox, Brave or even Vivaldi.

Also Brave uses uAssests (uBO's stock filterlists) for it's adblocker, so it seems our filter would contiune to work on Brave at least.
Vivaldi on the other hand has it's own adblocker that only supports network/cosmetic filters.

**Comment by MasterKia** [comment]
I'm open to any suggestions/changes for the list from you, especially regarding generic filters.
I learned a lot while collaborating with you on various sites, and I'm looking forward for more collaboration going forward.
