### ISSUE TITLE
Ads by YektaNet CDN needs to add to the list

### ISSUE THREAD

**Issue by sadeq-n-yazdi** [nimasaj/uBOPa#61]
the `ad-management-cdn.yektanet.com` domain is a cdn for deliver ads for some website like entekhab.ir could you please add this to the list?

**Comment by nimasaj** [comment]
I cannot find any ads on `entekhab.ir`. Could you please provide a direct link to the page where it shows the unblocked ads?

**Comment by nimasaj** [comment]
No response after 19 days.
Not reproducible.
