### ISSUE TITLE
May you please add these domains to ads list

### ISSUE THREAD

**Issue by 0xRustlang** [nimasaj/uBOPa#7]
سلام
لطفا درصورت امکان این دامنه ها رو هم توی لیست تبلیغات تون قرار بدین

چند تا دامین ممکنه تکراری باشه با لیستتون ولی متاسفانه ابزار اتوماتیک برای چک کردنش نداشتم نتونستم از لیست پیشنهادیم غربالشون کنم

در آخر خیلی ممنون و
موفق و پاینده باشید

netbina.com
netbina.net

appsharj.com
api.appsharj.com

api.sanjagh.com
sanjagh.com
sanjagh.net

fastclick.click
fastclick.co

kaprila.com
landyab.com
tavoos.net
iranwebads.com
merita.ir
mihanclick.info
networksara.com
nextads.ir
popland.info
utop.ir
vatanclick.ir
weclick.ir
ad2ad.ir
adnegah.net
adsima.net
adpulse.ir
adtube.ir
clickyab.com
iprank.ir
impressions.ir
ipopup.ir
ipsell.ir
popupads.ir
irclick.net
persianrank.ir

persianstat.com
persianstat.ir

metrix.ir
analytics.metrix.ir

api.tapsell.ir
najva.com

adad.ir
s.adad.ir

با تشکر فراوان

**Comment by nimasaj** [comment]
سپاس برای گزارش و تهیه ی این لیست. بعضی از این دامنه ها در لیست وجود دارند، مانند 
netbina, kaprilla و sanjagh.
 یکسری از دامنه ها، یا مربوط به ایران نیستند یا فعال نیستند مانند 
fastclick

برای بقیه ی دامنه ها لطف کن لیست وبسایت های که تبلیغات از روی این دامنه ها روشون دیده میشه رو قرار بده. 

سپاس

**Comment by 0xRustlang** [comment]
سلام
بله متاسفانه به دلیل مشکلات نتونستم کامل چک و غربالشون کنم

راستش اینا لاگ های ادبلاکر سیستمی من هست که با دی ان اس کار میکنه و پارسال جمعشون کردم

به همین دلیل نمیدونم دامنه هایی که این سرویس هارو استفاده میکنند کدوم سایتا هستن

خیلی ممنونم
موفق باشید

**Comment by nimasaj** [comment]
بیشتر دامنه های لیست شما که در زمینه ی تبلیغات بودند اضافه شدند
https://github.com/nimasaj/uBOPa/commit/e1d8a9ea24d2d732336533b428ce84e73773183c

**Comment by 0xRustlang** [comment]
لطف کردین
خیلی ممنون از زحماتتون
