### ISSUE TITLE
May you please create a simple url list for dns based blockers?

### ISSUE THREAD

**Issue by 0xRustlang** [nimasaj/uBOPa#8]
سلام
توی لیستتون خیلی سایتایی هست که صرفا کارشون تبلیغات کلیکی هست

امکانش هست براتون لطف کنین که اون سایتایی که فقط تبلیغات کامل هستن (اد نتورک هستن) رو توی یه لیست جدا فقط آدرسشون رو مثل این لیست درست کنین؟

https://github.com/farrokhi/adblock-iran/blob/master/pihole.txt

خیلی ممنون میشم و هیلی فوق العاده میشه همچین چیزی

**Comment by nimasaj** [comment]
انجام شد.
http://mynext.pro/uBOPa_Pihole.txt

**Comment by 0xRustlang** [comment]
واقعا ممنونم
