### ISSUE TITLE
unbreak code for wired.com

### ISSUE THREAD

**Issue by MasterKia** [nimasaj/uBOPa#9]
These filters from [uBOPa.txt](https://raw.githubusercontent.com/nimasaj/uBOPa/master/uBOPa.txt), block the "More from Wired" section in [wired.com](https://wired.com):
```
*##*[class^="ad_"]
*##*[class*="_ads "]
*##*[class*="-ads "]
*##*[class$="-ad"]
```

These codes unbreak them:
```
wired.com#@#*[class^="ad_"]
wired.com#@#*[class*="_ads "]
wired.com#@#*[class*="-ads "]
wired.com#@#*[class$="-ad"]
```

**Comment by nimasaj** [comment]
Thanks for reporting the issue. Even though the following two filters were not detected on my side, but since the whitelist is not bringing back the ads, all of them are added on f04369d.
```
wired.com#@#*[class*="_ads "]
wired.com#@#*[class*="-ads "]
```
